-- MySQL Script generated by MySQL Workbench
-- Thu Mar 25 12:10:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FitTrainer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FitTrainer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FitTrainer` DEFAULT CHARACTER SET utf8 ;
USE `FitTrainer` ;

-- -----------------------------------------------------
-- Table `FitTrainer`.`Gyms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FitTrainer`.`Gyms` (
  `GymId` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `GymName` VARCHAR(45) NOT NULL,
  `Avatar` BLOB NOT NULL,
  `JoinDate` DATETIME NULL,
  PRIMARY KEY (`GymId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FitTrainer`.`Trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FitTrainer`.`Trainers` (
  `TrainerId` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Age` INT NULL,
  `Avatar` BLOB NULL,
  PRIMARY KEY (`TrainerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FitTrainer`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FitTrainer`.`Clients` (
  `ClientId` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `JoinDate` DATETIME NULL,
  `Age` INT NULL,
  `Goal` VARCHAR(45) NULL,
  `Avatar` BLOB NULL,
  PRIMARY KEY (`ClientId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
